## PURPOSE OF THIS NOTEBOOK: 

The goal is to create a pitstop calculator based on telemetry data. It will report: 
1. average fuel consumption 
2. fuel consumption needed to add a lap before pitstop
3. total time estimated from per lap fuel saved
4. laptime expected for level of fuel save

### Factors I would need to calculate to complete this 
1. rate of acceleration

### NOTES: 
1. Data was collected varying frequencies. Given we know the frequency cycle rates, the formula to conver to seconds will be (F = 1/T) 
2. Tables labeled as Events report the event in seconds

## Step 01: Explore Data

In [2]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# import the data we need 

# Lap, this has the time in seconds where the lap started as well as the lap number, will be used as a primary indicator for position 
lap = pd.read_csv("data/Lap.csv")

# Fuel Level, the fuel level needed, Frequency is 20
fuel_level = pd.read_csv("data/Fuel Level.csv")

In [6]:
lap.head()

         ts  value
0   14.6425      0
1  238.5600      1
2  345.8400      2
3  452.9800      3
4  559.9200      4

In [12]:
fuel_level.shape

(50908, 1)

In [13]:
fuel_level

           value
0      92.000000
1      92.000000
2      92.000000
3      92.000000
4      92.000000
...          ...
50903  16.962720
50904  16.962633
50905  16.962545
50906  16.962456
50907  16.962368

[50908 rows x 1 columns]

In [17]:
50908 * .05 / 60

42.42333333333333

In [19]:
# Create new row, ts for fuel_level, will represent the amount of time in seconds. 
# we know the frequency is 20, which means we get a reading every .05 seconds (using the frequency equation)
fuel_level['ts'] = .05 * fuel_level.index

In [37]:
# Check to insure seconds are generated correctly 
fuel_level[fuel_level['ts'] > 44.99]

           value       ts
900    92.000000    45.00
901    92.000000    45.05
902    92.000000    45.10
903    92.000000    45.15
904    92.000000    45.20
...          ...      ...
50903  16.962720  2545.15
50904  16.962633  2545.20
50905  16.962545  2545.25
50906  16.962456  2545.30
50907  16.962368  2545.35

[50008 rows x 2 columns]

In [23]:
2545.35 / 60

42.4225